# Generated by Django 3.2 on 2021-05-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminute',
            old_name='meetingtype',
            new_name='meetingid',
        ),
    ]
