# Generated by Django 3.2 on 2021-05-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_rename_minute_meetingminute_minutestext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminute',
            old_name='meetingattendance',
            new_name='attendance',
        ),
    ]
